### PR TITLE
Set Postgres port to bind only on localhost

### PR DESCRIPTION
**Pull request by jesseops**
## Background

We opened up this port so we could get metrics, but missed in review that this binds to _all_ ports.

## Impact

Makes the Postgres port only bind on _localhost_

## Risk

Will cause a Postgres restart when this applies

## Testing

Run an update with this version and observe postgres is bound only to localhost

### CODE REVIEW

**Comment by jesseops** [comment]
Screenshot from 2023-01-27 10-35-44

image

image

Looks like this doesn't impact the app, as expected (the app hits the container directly)

**Review by Michael-Burke — APPROVED** [review]
LGTM; simple change restricting the port binding

**Review by BadgerOps — APPROVED** [review]
good catch here

**Review by m4l1c3 — APPROVED** [review]
💪

**Pull request merged**
