### PR TITLE
OPS-350: PGVector Enable

### PR DESCRIPTION
**Pull request by jjzabkar-plextrac**
Companion PR: https://github.com/PlexTrac/product-core-backend/pull/5818/files

### What

Enable `pgvector` Postgres database extension.

### Why

In order to use a vector column within the Core db, we must run the `create extension vector;` command. But the catch is that this must be run as a superuser. The core_admin user does not have high enough privileges to run that command, so we cannot run it as part of a normal schema migration.

We also should not run it via SaltStack ([example](https://github.com/PlexTrac/infra-saltstack/pull/434)); SaltStack should be invoked by the manager util. 

## Jira/Cloudenablement Issues
Please put links to the Jira issues that prompted this PR
- https://plextrac.atlassian.net/browse/AI-102
- https://github.com/PlexTrac/cloudenablement-docs/issues/350

### CODE REVIEW

**Review by jjzabkar-plextrac — COMMENTED** [review]
Block on Reagan merging a "dummy" version of `pg:superuser:bootstrap`

**Review by rkeeler — CHANGES_REQUESTED** [review]
Requesting changes to prevent unintended merge. I'm working on backporting a no-op version of that npm script so that we are able to merge this PR with zero side effects.

**Comment by jjzabkar-plextrac** [comment]
FYI passing ownership of this PR to CloudOps. Per synchronous conversation on 21-June, Ops will take ownership of merging this PR. The team agreed that the timeline to merge this PR is **after** the SaltStack changes are merged (ETA week of 24-June)

CC @Michael-Burke / @StevenPaugh / @rkeeler

**Comment by jjzabkar-plextrac** [comment]
@StevenPaugh Friendly ping because I don't understand the deployment complexities here: What's blocking this merge?

**Comment by jjzabkar-plextrac** [comment]
Disregard: I see the plan here: https://plextrac.atlassian.net/wiki/spaces/PT/pages/3279486991/Rollout+Plan+-+PGVector+Event+Orchestrator+and+Ruxpin+Narratives+AI+Improvements

**Comment by jjzabkar-plextrac** [comment]
@rkeeler @StevenPaugh @Michael-Burke I see per our [Rollout Plan](https://plextrac.atlassian.net/wiki/spaces/PT/pages/3279486991/Rollout+Plan+-+PGVector+Event+Orchestrator+and+Ruxpin+Narratives+AI+Improvements#GA-Rollout-(July-16th-%5BinlineCard%5D-)) that we're just waiting on the July 16 GA date before clicking merge. Checking in: Are there any other blockers?

**Comment by Michael-Burke** [comment]
Reviewed and added change to the image used for Podman users.

**Review by rkeeler — APPROVED** [review]

**Pull request merged**
